services:
  rapdos-s-github-io:
    container_name: rapdos-s.github.io
    image: node:latest
    volumes:
      - ../app:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
